# Generated by Django 5.1.3 on 2024-12-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jugador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('idmercado', models.AutoField(db_column='idMercado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mercado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('tiempoobtencion', models.IntegerField(blank=True, db_column='tiempoObtencion', null=True)),
                ('adquisicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproducto',
            fields=[
                ('idtipoproducto', models.AutoField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugadormercado',
            fields=[
                ('idpersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GameGains.jugador')),
                ('compra', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jugadormercado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugadorproducto',
            fields=[
                ('idpersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GameGains.jugador')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jugadorproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productomercado',
            fields=[
                ('idmercado', models.OneToOneField(db_column='idMercado', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GameGains.mercado')),
                ('demanda', models.IntegerField(blank=True, null=True)),
                ('competencia', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'productomercado',
                'managed': False,
            },
        ),
    ]
